### ISSUE TITLE
Issue with n_obs with fixest::feglm(family = binomial(logit))

### ISSUE THREAD

**Issue by RichardPatterson** [larmarange/broom.helpers#303]
`fixest::feglm(family = binomial(logit))` drops observations from groups (fixed effects) that do not see a change in the (binary) outcome, but this doesn't seem to be reflected in the n_obs provided by `tidy_plus_plus()`

```r
library("fixest")
library("broom.helpers") # installed from GitHub

data(iris)

iris$bin_out = sample(c(0,1), nrow(iris), replace = TRUE)
iris$bin_out[1:50] = 0 # set setosa to have constant outcome and therefore dropped
iris$bin_out[150] = NA # add an NA for comparison

model = feglm(bin_out ~ Sepal.Length | Species, data = iris, family = binomial(logit))
#> NOTES: 1 observation removed because of NA values (LHS: 1).
#>        1 fixed-effect (50 observations) removed because of only 0 (or only 1) outcomes.

model$nobs
#> [1] 99
model$nobs_origin
#> [1] 150

tpp = tidy_plus_plus(model)
tpp$n_obs
#> Sepal.Length 
#>          149

attributes(tpp)$N_obs
#> [1] 149
```
The correct number of observations is 99 as returned by `model$nobs`. If I have understood correctly I think the issue results from `model_get_frame()` retrieving a data.frame with these observations still present (although the NA observation is correctly removed, leaveing n=149).

```r
stats::model.frame.default(
   model_get_terms(model), 
   data = eval(model$call$data, model$call_env)
   ) |>
  nrow()
#> [1] 149
```

I am not sure whether you would want to simply provide `model$nobs` as an attribute and not return the column of n_obs for these model types. 

There does appear to be a possible workaround solution, but I don't know if this would have other implications that I'm not aware of.

```r
# estimate with data.save = TRUE to access complete frame with n = 150
model2 = feglm(bin_out ~ Sepal.Length | Species, data = iris, family = binomial(logit), data.save = TRUE)
#> NOTES: 1 observation removed because of NA values (LHS: 1).
#>        1 fixed-effect (50 observations) removed because of only 0 (or only 1) outcomes.

# Seems to show observations removed from data
model2$obs_selection[[1]]
#>  [1]   -1   -2   -3   -4   -5   -6   -7   -8   -9  -10  -11  -12  -13  -14  -15
#> [16]  -16  -17  -18  -19  -20  -21  -22  -23  -24  -25  -26  -27  -28  -29  -30
#> [31]  -31  -32  -33  -34  -35  -36  -37  -38  -39  -40  -41  -42  -43  -44  -45
#> [46]  -46  -47  -48  -49  -50 -150

model2_data = model2$data
dim(model2_data)
#> [1] 150   6

model2_data = model2_data[-c(abs(model2$obs_selection[[1]])),]
dim(model2_data)
#> [1] 99  6

model2_data = stats::model.frame.default(
  model_get_terms(model),
  data = model2_data
)
dim(model2_data)
#> [1] 99  2
```

**Comment by larmarange** [comment]
Thanks @RichardPatterson 

You may have a look at #304

**Comment by larmarange** [comment]
Thanks for pointing this out.

Should be fixed by #305

**Comment by RichardPatterson** [comment]
The var_label returned by `tidy_plus_plus()` now appears to be correct, but I'm still not getting a reference row or the "clean" value labels (from factor levels). 

Again, this only seems to be effecting models with missing data so in the example from above, the first model/output seems fine with no missing data. In the second case the missing data appears to lead to issues,

```r
#remotes::install_github("larmarange/broom.helpers", force=TRUE)
library("fixest")
library("broom.helpers")
library("labelled")

data(iris)
var_label(iris$Sepal.Length) <- "Length of the sepal"
iris$bin_out = sample(c(0,1), nrow(iris), replace = TRUE)
iris$Species = factor(iris$Species)

model1 = feglm(bin_out ~ Sepal.Length + Species, data = iris, family = binomial(logit))
tpp1 = tidy_plus_plus(model1)

subset(tpp1, select = c(var_label, contrasts, contrasts_type, reference_row, label))
#> # A tibble: 4 × 5
#>   var_label           contrasts       contrasts_type reference_row label        
#>   <chr>               <chr>           <chr>          <lgl>         <chr>        
#> 1 Length of the sepal <NA>            <NA>           NA            Length of th…
#> 2 Species             contr.treatment treatment      TRUE          setosa       
#> 3 Species             contr.treatment treatment      FALSE         versicolor   
#> 4 Species             contr.treatment treatment      FALSE         virginica
```

Adding some missing data seems to cause problems.

```r

iris$bin_out[150] = NA
model2 = feglm(bin_out ~ Sepal.Length + Species, data = iris, family = binomial(logit))
#> NOTE: 1 observation removed because of NA values (LHS: 1).

tpp2 = tidy_plus_plus(model2)

subset(tpp2, select = c(var_label, contrasts, contrasts_type, reference_row, label))
#> # A tibble: 3 × 5
#>   var_label           contrasts contrasts_type reference_row label              
#>   <chr>               <chr>     <chr>          <lgl>         <chr>              
#> 1 Length of the sepal <NA>      <NA>           NA            Length of the sepal
#> 2 Species             <NA>      <NA>           NA            Speciesversicolor  
#> 3 Species             <NA>      <NA>           NA            Speciesvirginica
```

I'm not really sure but I think the issue is that attributes are being lost from the model matrix (as well as the model frame - which you've addressed).

```r
model_get_model_matrix(model1)
#>     (Intercept) Sepal.Length Speciesversicolor Speciesvirginica
#> 1             1          5.1                 0                0
#> 2             1          4.9                 0                0
#> 3             1          4.7                 0                0
#> 4             1          4.6                 0                0
#> 5             1          5.0                 0                0
...
#> 146           1          6.7                 0                1
#> 147           1          6.3                 0                1
#> 148           1          6.5                 0                1
#> 149           1          6.2                 0                1
#> 150           1          5.9                 0                1
#> attr(,"assign")
#> [1] 0 1 2 2
#> attr(,"contrasts")
#> attr(,"contrasts")$Species
#> [1] "contr.treatment"

model_get_model_matrix(model2)
#>     (Intercept) Sepal.Length Speciesversicolor Speciesvirginica
#> 1             1          5.1                 0                0
#> 2             1          4.9                 0                0
#> 3             1          4.7                 0                0
#> 4             1          4.6                 0                0
#> 5             1          5.0                 0                0
...
#> 146           1          6.7                 0                1
#> 147           1          6.3                 0                1
#> 148           1          6.5                 0                1
#> 149           1          6.2                 0                1
```

Again, thanks for your time and effort.

**Comment by larmarange** [comment]
Thanks again for the feedback. Should be fixest with #306
